# CTNx Audio Engine config file - Ambient layer

### HOW TO: ###################################################################
# Sections may be commented by default with an initial # character.
# Remove the initial # character to set the entire sections block and its flags
# -----------------------------------------------------------------------------
# Syntax:
# [ID]
# flag = value
# another_flag = value
###############################################################################

### SUPPORTED FLAGS: ##########################################################
# shuffle: Shuffle an SFX ID with one of the given IDs in the array. IDs MUST
# be numbers ONLY and MUST NOT contain any special character like - or _.
# This flag MUST NOT be used in pair with 'sequential'.
# -----------------------------------------------------------------------------
# sequential: Sequentially playback an SFX ID with the ones provided in the
# array. IDs MUST be numbers ONLY and MUST NOT contain any special character
# like - or _. This flag MUST NOT be used in pair with 'shuffle'.
# -----------------------------------------------------------------------------
# fade_in: Fade in the track on play. The value MUST be a floating point
# number and if 0.0 ( default ) then the track will NOT fade.
# -----------------------------------------------------------------------------
# fade_out: Fade out the track on stop. The value MUST be a floating point
# number and if 0.0 ( default ) then the track will NOT fade.
# -----------------------------------------------------------------------------
# volume: Allow volume to be adjusted for a specific track.
###############################################################################

# Example
# -----------------------------------------------------------------------------
#[field_123]
#shuffle = [ "field_121", "field_122", "field_124" ]
#sequential = [ "field_121", "field_122", "field_124" ]
#fade_in = 0.0
#fade_out = 0.0
#volume = 50
